### PR TITLE
T/3

### LINKED ISSUE #3: Handle spellchecking, autocorrect and autocompletion
As I mentioned in #2 it makes sense to handle these features in this package.

However, while typing should be straightforward (with the exception of composition, but we should be fine here too), spellchecking and autocorrect may be a bit tricky because they may cover a bigger part of a tree. Additionally, I'm a bit worried about touch devices with onscreen keyboards, so they will need to be checked separately.

Note: If you ever test autocorrection on touch devices make sure to use English keyboard because (at least on iOS) it has more features than the Polish one.

### PR DESCRIPTION
**Pull request by f1ames**
Tests: Introduced integration tests for spellchecking. Closes #3.

---

### Additional information

Those tests covers only cases with spellchecking corrections on a non-styled text. The styled one will be covered in #74.

### CODE REVIEW

File: tests/manual/spellchecking.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+window.setInterval( function() {
+	console.log( getData( window.editor.document ) );
+}, 3000 );
+
+ClassicEditor.create( document.querySelector( '#editor' ), {
+	plugins: [ Enter, Typing, Paragraph, Undo, Bold, Italic, Heading ],
+	toolbar: [ 'headings', 'bold', 'italic', 'undo', 'redo' ]
+} )
+	.then( editor => {
```
Comment (Reinmar) [inline tests/manual/spellchecking.js]: Don't indent these lines.

File: tests/manual/spellchecking.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+## Input (typing) feature with spell checking
+
+Try to correct all misspelled words using native spell checking mechanism in the browser.
+
+* Words should be corrected and selection placed after corrected word. _In Safari selection is placed
+at the beginning of corrected word.
```
Comment (Reinmar) [inline tests/manual/spellchecking.md]: Missing terminating `_`?

Comment (Reinmar) [inline tests/manual/spellchecking.md]: Also, if this is a bug, you can link to the issue on GH to explain that this is a bug.

File: tests/spellchecking.js [hunk 3]
```diff
@@ -0,0 +1,259 @@
...
+		} );
+	} );
+
+	describe( 'Plain text spellchecking (insertText)', () => {
+		// This tests emulates spellchecker correction on non-styled text by inserting correction text via native 'insertText' command.
+
+		it( 'should replace with longer word (collapsed)', ( done ) => {
+			emulateSpellcheckerInsertText( editor, 0, 12, 12, 'e' );
+
+			setTimeout( () => {
```
Comment (Reinmar) [inline tests/spellchecking.js]: Could we avoid using `setTimeout()`? Perhaps the check can be done on `editor.document#changeDone`? It'll be more reliable (if the timeout is longer). Also, it'd be good to know that the changes are done immediately.

PS. When using listener to check such a thing there may be issues with the event being fired after the test terminated. This will cause crashing tests in an unpredictable manner. So make sure to use a proper `afterEach()` with editor destroy. Also, you can secure it by using `once()`.

Comment (f1ames) [inline tests/spellchecking.js]: I made use of `changesDone` event.  I used `once` and then `off` in `afterEach` instead of destroying editor every time.
