### PR TITLE
Typing improvements

### LINKED ISSUE #100: Basic styling disables browser's native word correction
## Steps to reproduce
1. Type a word with a mistake, for example "testter".
2. Select it and apply bold with CTRL + B.
3. Right click on a word and try to correct it with native browser spell checker.

## Current result
Nothing happens.

## Expected result
Word should change to chosen one.

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed a range of issues when typing or using a spellchecker on styled words leads to errors. Closes #100. Closes ckeditor/ckeditor5#491.

---

### Additional information
It also closes main issue reported in: https://github.com/ckeditor/ckeditor5/issues/491. Test case reported by @Reinmar https://github.com/ckeditor/ckeditor5/issues/491#issuecomment-312657159 looks like it's out of the scope of this issue - I've tested it a little and insertion to the model looks correct. It should be reported as separate ticket.

When this PR will be merged I'll create some follow ups:
 * issue about using new DomConverter instance, it is described also here: https://github.com/ckeditor/ckeditor5-engine/issues/993#issuecomment-315696765,
 * when auto correcting bolded word, that is placed at the end of the paragraph,  mutation of all paragraphs are fired, this should be handled separately,
 * selection is sometimes lost/in incorrect place when auto correcting bolded word, when output word is shorter than input one.

### CODE REVIEW

**Comment by Reinmar** [comment]
☕️  and 🤞 ... starting the review :D

**Comment by Reinmar** [comment]
Would be good to have a manual test for a couple of cases.

**Comment by Reinmar** [comment]
Composition at the end of such link doesn't work (this is Spanish ISO keyboard): jul-20-2017 12-20-11

However, this has no chance to work because the engine rerenders the content after "`" press. There's https://github.com/ckeditor/ckeditor5-engine/issues/460 but it's only about selection. Here we have a proof that we also need to avoid rerendering elements.

**Comment by Reinmar** [comment]
This still doesn't work:

jul-20-2017 12-27-21

**Comment by Reinmar** [comment]
I've checked a bit the mutations of all paragraphs and it's interesting, cause it says that nothing's changed:
image

So this must be some issue in the mutation observer. As you wrote, worth followup.

**Comment by Reinmar** [comment]
I created the followup for the `MutationObserver`: https://github.com/ckeditor/ckeditor5-engine/issues/1031.

**Comment by Reinmar** [comment]
I pushed t/1031 to ckeditor5-engine and it fixes the mutation observer. With that fix all seem to work except:

jul-20-2017 14-11-30

File: src/input.js [hunk 1]
```diff
@@ -142,11 +143,104 @@ class MutationHandler {
...
+		// Create fresh DomConverter so it will not use existing mapping and convert current DOM to model.
+		// This wouldn't be needed if DomConverter would allow to create fresh view without checking any mappings.
+		const freshDomConverter = new DomConverter();
+		const modelFromCurrentDom = this.editor.data.toModel( freshDomConverter.domToView( domMutationCommonAncestor ) ).getChild( 0 );
+
+		// Current model.
+		const currentModel = this.editor.editing.mapper.toModelElement( mutationsCommonAncestor );
+
+		// Get children from both ancestors.
+		const modelFromDomChildren = [ ...modelFromCurrentDom.getChildren() ];
```
Comment (Reinmar) [inline src/input.js]: TBH, I prefer Array.fromArray() because it's more straightforward.

File: src/input.js [hunk 2]
```diff
@@ -309,3 +354,152 @@ function compareChildNodes( oldChild, newChild ) {
...
+	return change;
+}
+
+// Returns first common ancestor of all mutations that is either {@link module:engine/view/containerelement~ContainerElement}
+// or {@link module:engine/view/rootelement~RootElement}.
+//
+// @private
+// @param {Array.<module:engine/view/observer/mutationobserver~MutatedText|
+// module:engine/view/observer/mutationobserver~MutatedChildren>} mutations
+function getMutationsCommonAncestor( mutations ) {
```
Comment (Reinmar) [inline src/input.js]: Can't we simply get common ancestor of all nodes involved in all mutations? AFAIU this can be simply done by:

`mutation1.node.getCommonAncestor( mutation2.node ).getCommonAncestor( mutation3.node )` etc.

Until the point when root is returned.

File: src/input.js [hunk 3]
```diff
@@ -309,3 +354,152 @@ function compareChildNodes( oldChild, newChild ) {
...
+	}
+
+	return true;
+}
+
+// Returns true if provided array contains only {@link module:engine/model/text~Text model text nodes}.
+//
+// @param {Array<module:engine/model/node~Node>} children
+// @returns {Boolean}
+function containsOnlyTextNodes( children ) {
```
Comment (Reinmar) [inline src/input.js]: Array.from( children ).every( child => child.is( 'text' ) )

**Comment by Reinmar** [comment]
OK, this is enough for now. I simplified a good part of the code and fixed some tests to be safer. It's still missing a manual test, but it can be a followup to not keep it open forever.

**Comment by Reinmar** [comment]
Interesting followup – https://github.com/ckeditor/ckeditor5-list/issues/70. A bug in the list converter.

**Comment by Reinmar** [comment]
I also reported the followup with the image crashing the editor: https://github.com/ckeditor/ckeditor5-image/issues/127.
