### PR TITLE
T/48

### LINKED ISSUE #48: Expose the `input` command
Currently, the input feature simply listens on the view events and transforms them into changes on the model. However, this is a pretty complex logic and it's hard to reproduce those behaviours in tests.

The idea is to expose the `input` command, just like `delete` command is exposed by the delete feature.
## Naming

I've been also considering `insertText` command, however, I see it a bit differently – like `insertHtml`. Both are used in CKE4 for pasting purposes, so e.g. they create separate undo steps and may process the content in some way.

Therefore, for now, let's call the command like we called the feature, so `input`. If we'll see a chance to somehow squash the two things together, then we may do this in the future.
## The interface

From the command's perspective alone, it should simply accept a:
- text to insert,
- target ranges (optional – if not passed, it can use the selection).

(Note: Target range concept comes from the native `beforeinput` event: https://github.com/ckeditor/ckeditor5-typing/issues/46)

So what the command will do is:
1. Delete contents of the target ranges.
2. Insert the text.
3. Increment the buffer.

However, I've got some doubts whether it will be possible to extract such command from the current input feature. I hope it will...

### PR DESCRIPTION
**Pull request by f1ames**
Feature: Introduced `InputCommand` used for typing handling. Closes #48.

### CODE REVIEW

File: src/inputcommand.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+	constructor( editor ) {
+		super( editor );
+
+		/**
+		 * Typing's change buffer used to group subsequent changes into batches.
+		 *
+		 * @protected
+		 * @member {typing.ChangeBuffer} #_buffer
+		 */
+		this._buffer = new ChangeBuffer( editor.document, editor.config.get( 'typing.undoStep' ) || 20 );
```
Comment (Reinmar) [inline src/inputcommand.js]: This should be given to the command as an option, not taken by it from the editor. A class like a command should depend on the world in as little details as possible.

File: src/input.js [hunk 2]
```diff
@@ -72,29 +55,28 @@ export default class Input extends Plugin {
...
+			this.editor.data.deleteContent( doc.selection, buffer.batch );
 		} );
 	}
 
 	/**
 	 * Handles DOM mutations.
 	 *
-	 * @param {Array.<engine.view.Document~MutatatedText|engine.view.Document~MutatatedChildren>} mutations
+	 * @param {Array.<module:engine/view/document~MutatatedText|module:engine/view/document~MutatatedChildren>} mutations
+	 * @param {module:engine/controller/editingcontroller~EditingController} viewSelection
```
Comment (Reinmar) [inline src/input.js]: Wrong type.

File: src/inputcommand.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+	/**
+	 * Executes the input command. It replaces the content within the given range with the given text.
+	 * Replacing is a two step process, first content within the range is removed and then new text is inserted
+	 * on the beginning of the range (which after removal is a collapsed range).
+	 *
+	 * @param {Object} [options] The command options.
+	 * @param {String} [options.text=''] Text to be inserted.
+	 * @param {module:engine/model/range~Range} [options.range=null] Range in which the text is inserted. Defaults
+	 * to first range in the current selection.
+	 * @param {module:engine/model/position~Position} [options.selectionAnchor] Selection anchor which will be used
```
Comment (Reinmar) [inline src/inputcommand.js]: This command should not need to accept the selection anchor (I don't even know how it's used). It should calculate the result selection position based on the given target range to remove and text which it's inserting. At least... I hope that it can be done this way ;>

File: src/input.js [hunk 4]
```diff
@@ -211,20 +184,11 @@ class MutationHandler {
...
-		const insertedText = mutation.newText.substr( firstChangeAt, insertions );
-		this._insert( modelPos, insertedText );
-
-		// If there was `viewSelection` and it got correctly mapped, collapse selection at found model position.
-		if ( modelSelectionPosition ) {
-			this.editing.model.selection.collapse( modelSelectionPosition );
-		}
+		this.editor.execute( 'input', {
+			text: mutation.newText.substr( firstChangeAt, insertions ),
+			range: deletions > 0 ? ModelRange.createFromPositionAndShift( modelPos, deletions ) : null,
```
Comment (Reinmar) [inline src/input.js]: Please move the consts out of this object literal. Those variables can make the code more readable (and easier to debug) thanks to their names.

File: src/inputcommand.js [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+ * @module typing/inputcommand
+ */
+
+import Command from '@ckeditor/ckeditor5-core/src/command/command';
+import ChangeBuffer from './changebuffer';
+
+/**
+ * The input command. Used by the {@link module:typing/input~Input input feature} to handle typing.
+ *
+ * @extends core.command.Command
```
Comment (Reinmar) [inline src/inputcommand.js]: Old notation. Now should be `@extends {module:blebleble~Command}`.

File: src/inputcommand.js [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+	 * @param {module:core/editor/editor~Editor} editor
+	 */
+	constructor( editor ) {
+		super( editor );
+
+		/**
+		 * Typing's change buffer used to group subsequent changes into batches.
+		 *
+		 * @protected
+		 * @member {typing.ChangeBuffer} #_buffer
```
Comment (Reinmar) [inline src/inputcommand.js]: Old type notation as well.

File: src/inputcommand.js [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+	}
+
+	/**
+	 * Executes the input command. It replaces the content within the given range with the given text.
+	 * Replacing is a two step process, first content within the range is removed and then new text is inserted
+	 * on the beginning of the range (which after removal is a collapsed range).
+	 *
+	 * @param {Object} [options] The command options.
+	 * @param {String} [options.text=''] Text to be inserted.
+	 * @param {module:engine/model/range~Range} [options.range=null] Range in which the text is inserted. Defaults
```
Comment (Reinmar) [inline src/inputcommand.js]: I think that the range could default to first selection's range if not passed. Will be pretty useful.

Comment (f1ames) [inline src/inputcommand.js]: It does, it is stated in the comment: _Range in which the text is inserted. Defaults to first range in the current selection._ However, it is no stated in the param specs, should it be like `[options.range] plus description` or something like `[options.range=document.selection.getFirstRange()]`?

File: src/inputcommand.js (hunk 3 above)
Comment (f1ames) [inline src/inputcommand.js]: For simple case it works as you described. But there are cases like e.g. spell checking and probably it was the reason that [modelSelectionPosition](https://github.com/ckeditor/ckeditor5-typing/blob/master/src/input.js#L207) was introduced at the first place.
If there is text like `athat` and spell checking is used to replaced it with `that`, based on mutation there is range like `[a]that` and inserted text is empty. I am not sure if it is possible to calculate proper selection position based on that (I assume after replacing the position should be after replaced/corrected word)?
I may propose changing the option name to e.g. `targetPosition` which may be a little more meaningful, unless ofc  there is a way to correctly calculate selection in those cases?

**Comment by f1ames** [comment]
Pushed changes suggested by @Reinmar. There are two things which may require further discussion or some changes, see: https://github.com/ckeditor/ckeditor5-typing/pull/71#discussion_r101022539 and https://github.com/ckeditor/ckeditor5-typing/pull/71#discussion_r101020183.

File: src/input.js [hunk 8]
```diff
@@ -107,45 +108,45 @@ class MutationHandler {
...
 		 */
-		this.buffer = buffer;
+		this.editing = this.editor.editing;
 
 		/**
-		 * The number of inserted characters which need to be fed to the {@link #buffer change buffer}.
+		 * The change buffer;
 		 *
-		 * @member {Number} #insertedCharacterCount
+		 * @type {module:typing/changebuffer~ChangeBuffer} #buffer
```
Comment (Reinmar) [inline src/input.js]: Should be `@member`.

**Comment by f1ames** [comment]
Corrected the docs.

File: src/inputcommand.js (hunk 7 above)
Comment (Reinmar) [inline src/inputcommand.js]: Can be `[options.range] plus description`. Can also be the latter. But definitely not `=null` :D

File: src/inputcommand.js (hunk 3 above)
Comment (Reinmar) [inline src/inputcommand.js]: If you replace `athat` with `that` and according to the engine, the selection should be after "that", then the passes `options.range` should be `[athat]` and `options.text = 'that'`. The input command will remove the whole "athat", insert "that" and place the selection after "that". You don't need `options.selectionAnchor` for that.

I understand that this may not be fully intuitive at first, but think about this from OT perspective. If you're fixing the word's "athat" spelling you're replacing it with "that". The whole word, not just a single letter. This may be crucial when resolving some conflicting changes and, in general, is more semantical.

Hence, try to get rid of `selectionAnchor`. I wrote before that I'm not sure if it's doable, though, because I haven't checked input feature's implementation. Why did you implement it in the first place? Was it already strictly required by what the mutation observer produces?

**Comment by Reinmar** [comment]
I commented on the two aspects you mentioned. The most important bit is to try to avoid the 3rd option.

Also, you'll need to resolve conflicts now.

PS. You may not know yet  – you shouldn't rebase a branch once it's after any review because this will break comments on GH. So merge master to it.

File: src/inputcommand.js (hunk 7 above)
Comment (f1ames) [inline src/inputcommand.js]: Makes perfect sense, I'll go with first one.

File: src/inputcommand.js (hunk 3 above)
Comment (f1ames) [inline src/inputcommand.js]: Ok, I was relying too much on what information we already have calculated based on mutations.

For case described above the mutation provided by mutation observer is:

```
newText: "foo that bar"
node: Text
oldText: "foo athat bar"
type: "text"
```

I assume based only on this information it is not possible to reliable calculate the range and text which will be passed to `InputCommand`, unless we may assume that the range (and text) will consist of all words which were modified by mutation. If not I think the mutation observer should be modified to provide some additional information in mutations. 

The other spellchecking cases to consider are:
`Foo hous a` -> `Foo house a`
`Foo hous e` -> `Foo house`
`Foo athat`   -> `Food that`
`Foo xhat` -> `Foo chat`

Comment (f1ames) [inline src/inputcommand.js]: Hmmm, forgot about `viewSelection` which is passed along with mutations, will see if it will help solve this one :)

**Comment by f1ames** [comment]
I moved `buffer` back to `InputCommand` as I earlier misunderstood this comment https://github.com/ckeditor/ckeditor5-typing/pull/71#pullrequestreview-21564067. Updated unit tests accordingly.
We decide that `InputCommand` would have optional parameter/option `resultPosition`, if given, after text processing the selection is set using `resultPosition`.

**Comment by Reinmar** [comment]
I fixed the API docs a bit.

I didn't like one thing – the fact that `options.text` is optional. Executing the command without the text doesn't make sense because it doesn't do anything.

Another thing is that the range doesn't have to be checked too. I don't see a case today in which selection could not have any range in it. The document selection will return so called "default range" and if you provide any custom selection, with no range inside, let the code throw. At least we'll know the situation occurs so we'll be able to fix it. Now, it's a silent error.

**Comment by Reinmar** [comment]
Of course, let's do that unless we already see that there may be no range or no text :D. Let's then think how to handle this situation.

**Comment by f1ames** [comment]
> Executing the command without the text doesn't make sense because it doesn't do anything.

Well, it does not look like making much sense indeed. But without checking if text was passed and passing non-collapsed range at the same time to the command will result in removing the content within the range without inserting anything. So we should decide if it is an acceptable behavior or some error should be thrown if text was not passed.
It is the same behavior as passing `text = ''`, I am not sure if we should differentiate this two cases or assume the it should behaves the same.

File: src/inputcommand.js [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+	 * should be placed after the insertion. If not specified, the selection will be placed right after
+	 * the inserted text.
+	 */
+	_doExecute( options = {} ) {
+		const doc = this.editor.document;
+		const text = options.text;
+		const range = options.range || doc.selection.getFirstRange();
+		const resultPosition = options.resultPosition;
+
+		let textInsertions = 0;
```
Comment (Reinmar) [inline src/inputcommand.js]: Is it needed?

**Comment by f1ames** [comment]
Made `options.text` optional and defaults to `''` as we discussed earlier.
