### PR TITLE
T/86 InputCommand should accept range instead of position as a parameter.

### LINKED ISSUE #54: [Safari] Selection lands at the beginning of corrected word after using spell checker
oct-17-2016 14-28-01

I tested it after we closed https://github.com/ckeditor/ckeditor5-typing/pull/53.

It also doesn't work great in Firefox, but at least the selection that you get is the position of selection when you open the context menu. So this makes some sense. What you get in Safari doesn't make sense though.

### LINKED ISSUE #86: InputCommand should accept range instead of position as a parameter.
While `InputCommand` uses position to restore selection (https://github.com/ckeditor/ckeditor5-typing/blob/master/src/inputcommand.js#L67) it works in most cases due to the fact that selection is collapsed after text insertion.

The case where selection is not collapsed is MacOS accent panel. While navigating through the accents, native selection is non-collapsed containing newly inserted accent. While the input command uses position, it collapses selection in a view/model which causes additional rendering step (because selection in DOM is not collapsed). Using `Range` instead of `Position` will prevent this situation.

It is important due to the fact that rerendering selection during the composition breaks it in Safari.

### PR DESCRIPTION
**Pull request by f1ames**
Fix: `InputCommand` now accepts `Range` instead of `Position` as a parameter. Closes #86. Closes #54.

BREAKING CHANGE: `InputCommand` `options.resultPosition` was replaced with `options.resultRange`.

---

### Additional information

This fixes #54, however in a way it works now same as natively in Safari - after correction the whole word is selected.

### CODE REVIEW

File: tests/manual/86/1.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+/**
+ * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
+ * For licensing, see LICENSE.md.
+ */
+
+/* globals console, window, document */
+
+import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classic';
+import Enter from '@ckeditor/ckeditor5-enter/src/enter';
```
Comment (Reinmar) [inline tests/manual/86/1.js]: Use the essential preset + paragraph instead of these 4 plugins.

Comment (Reinmar) [inline tests/manual/86/1.js]: You can also update all other manual tests.

**Comment by Reinmar** [comment]
Two things:

* let's switch to using the essentials preset (remember to add it as a dev dependency),
* I can see you didn't have to change any test after changing the option name which means that there's no test for it in the command's tests ;>

Other than that, everything works fine, so you can merge the ticket (don't forget to copy the message) once you fix the tests.

**Comment by f1ames** [comment]
Ok, manual tests updated to use essentials preset. Added 2 unit tests covering `resultRange`.
